# Generated by Django 4.2.10 on 2026-01-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, default='/static/image/default.webp', null=True, upload_to='avatar/'),
        ),
    ]
