# Generated by Django 4.2.10 on 2026-01-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, default='static/image/default.webp', null=True, upload_to='avatar/'),
        ),
    ]
