# Generated by Django 4.2.10 on 2026-02-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_article_tag_alter_user_avatar_comment_article_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisitStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('visit_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'daily_visit_stat',
                'verbose_name_plural': 'daily_visit_stat',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'user'},
        ),
    ]
