"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 4.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k0rkh2$ji7a-o#^d0@au(3-ds^i0c3-xm%7!jm*+1-8ml-rn%+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app01',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # 鍙互璁╂ā鏉块兘鑷姩load static
            'builtins': [
                'django.templatetags.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'blog',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
# 闈欐€佹枃浠禪RL
STATIC_URL = '/static/'
# 闈欐€佹枃浠剁洰褰?
STATICFILES_DIRS = [BASE_DIR / 'static']

# media
MEDIA_URL = '/media/'
# 濯掍綋鏂囦欢鐩綍
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 鍙戦€侀偖绠遍厤缃?
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # 鍙戦€侀偖绠卞悗绔?
EMAIL_USE_TLS = True  # 鏄惁浣跨敤TLS鍔犲瘑
EMAIL_HOST = 'smtp.qq.com'  # 鍙戦€侀偖绠变富鏈?
EMAIL_PORT = 587  # 鍙戦€侀偖绠辩鍙?
EMAIL_HOST_USER = '2331650385@qq.com'  # 鍙戦€侀偖绠辩敤鎴峰悕
EMAIL_HOST_PASSWORD = 'xstfedcneisidjfd'  # 鍙戦€侀偖绠辨巿鏉冪爜锛佷笉鏄疩Q瀵嗙爜
DEFAULT_FROM_EMAIL = '2331650385@qq.com'  # 榛樿鍙戦€侀偖绠?

# 鑷畾涔夌敤鎴锋ā鍨?
AUTH_USER_MODEL = 'app01.User'
# Redis（用于阅读量去重限流）
REDIS_HOST = '127.0.0.1'
REDIS_PORT = 6379
REDIS_DB = 0
REDIS_PASSWORD = '123456'

# 阅读量去重窗口（秒）
ARTICLE_READ_LIMIT_SECONDS = 3600

# 网站访问去重窗口（秒，按 IP）
SITE_VISIT_LIMIT_SECONDS = 3600
